version: '3'
services:
  eureka-server:
    build:
      context: .
      dockerfile: eureka-server/Dockerfile
    ports:
      - "8761:8761"
    networks:
      - car-network

  inventory-service:
    build:
      context: .
      dockerfile: inventory-service/Dockerfile
    depends_on:
      - eureka-server
    networks:
      - car-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka

  cars-service:
    build:
      context: .
      dockerfile: cars-service/Dockerfile
    depends_on:
      - eureka-server
    networks:
      - car-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
      - inventory-service
      - cars-service
    networks:
      - car-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka

networks:
  car-network: